Neos:
  RedirectHandler:
    NeosAdapter:
      enableRemovedNodeRedirect: true
      enableAutomaticRedirects: true
      restrictByNodeType:
        'Neos.Neos:Test.Redirect.RestrictedPage': true
      restrictByOldUriPrefix:
        'restricted-by-path': true

